### ISSUE TITLE
小米电视倒腾自定义图片屏保失败 xiaomi tv hack image screensaver failed

### ISSUE THREAD

**Issue by jollychang** [jollychang/jollychang.github.com#1]
**前情提要**
公司基本上每个会议室都有小米电视，然后最近我们想对于会议室做一些海报的推广，很自然的想到了小米电视来作为展示的入口。
之前小米电视是支持『[云相册照片自定义屏保](http://www.tvapk.net/thread-207299-1-1.html)』，但是最近广告越来越多，[取消了这个功能](http://bbs.xiaomi.cn/t-14529674-u30700297#comment_top)，我就在想有没有一些 Hack 的手段来做这个事情？但是最终都一一失败了，仅分享解题思路，欢迎大家献计献策。

**思路一：替换『时尚画报』已缓存的图片**

- adb 连上小米电视
  - 连续点击 5 次设置里的版本号
  - 安全页面开启 ADB 调试；
  - adb connect ip，比如 `adb connect 192.168.43.119`
  - `adb shell` find 一通，没有找到相关文件夹，而且没有 root 的话，很多目录访问不了

**思路二：劫持『时尚画报』的网络请求，替换将缓存的图片**

- adb 连接小米电视
- 安装类似 XX 桌面等可以进入 android 系统设置的应用
- Android 系统的 WiFi 设置面板设置代理信息
- 使用 Charles 等代理调试工具修改网络的代理资源请求 map local 到本地
- 替换[资源列表](https://gist.github.com/jollychang/668e6fb14b6ccad1f62c5e45ce0e69ed)和图片文件
![xnip2018-06-28_13-14-53](https://user-images.githubusercontent.com/64213/42014523-550287f0-7ad5-11e8-90e7-42d48960c8d3.jpg)
  - 还修改了本地 map 图片的 md5 值
但是依然未果，替换完成之后一直提示 『时尚画报』 加载高清图片中，而且应该触发了 httpdns 的逻辑，有时候会直接请求 ip 来获取资源

**思路三：Root**
不是很想做，但是 TBD

**Comment by pansila** [comment]
有更新么？我试了下可用用U盘做屏保，但还是不太方便，最好能方法2能走通，这样可以远程自动更新

**Comment by jollychang** [comment]
> 有更新么？我试了下可用用U盘做屏保，但还是不太方便，最好能方法2能走通，这样可以远程自动更新

不行，我们最后还是用 U 盘更新的

**Comment by materliu** [comment]
有什么更新吗，那岂不是要一直插着一个U盘。

**Comment by jollychang** [comment]
> 有什么更新吗，那岂不是要一直插着一个U盘。

还是需要插 U 盘。
